### PR TITLE
Status code on complete

### LINKED ISSUE #51: What is not traced
# Server
* URLs without mapping. see also #13
* ~~exceptions in handlers. see also #13, #50~~ - Traced by servlet filter `SpanFinishingFilter`.
* Exceptions added to `AsyncResponse#resume()` are not propagated to `onComplete` or `onError` async callbacks

# Client
* interceptors do not catch `UnknownHostException` #30
* ~~some impls do not allow to specify custom `ExecutorService` (which propagates active span), therefore when invoking multiple async requests at the same time created spans can have a wrong parent #37~~ CXF does not support this but it invokes filters in the same thread, however async response filter is executed in a different thread so it cannot close scopes!

### PR DESCRIPTION
**Pull request by pavolloffay**
Resolves #51

### CODE REVIEW

File: opentracing-jaxrs2-itest/common/src/main/java/io/opentracing/contrib/jaxrs2/itest/common/AbstractServerTest.java [hunk 1]
```diff
@@ -94,14 +97,11 @@ public void testAsyncError() {
         List<MockSpan> mockSpans = mockTracer.finishedSpans();
         Assert.assertEquals(1, mockSpans.size());
         assertOnErrors(mockSpans);
-//        TODO resteasy and CXF do not propagate exception to the filter, https://issues.jboss.org/browse/RESTEASY-1758
-//        MockSpan mockSpan = mockSpans.get(0);
```
Comment (jpkrohling) [inline opentracing-jaxrs2-itest/common/src/main/java/io/opentracing/contrib/jaxrs2/itest/common/AbstractServerTest.java]: Is this commented out code going to replace the non-commented out once the linked JIRA is fixed? If so, it would probably be better to have two tests, one marked with `@Ignored`.

Comment (pavolloffay) [reply opentracing-jaxrs2-itest/common/src/main/java/io/opentracing/contrib/jaxrs2/itest/common/AbstractServerTest.java]: I think it's better, more visible to what needs to be fixed
