### PR TITLE
Fix client scope not being closed 

### LINKED ISSUE #78: ClientTracingFilter does not close activated Scope
ClientTracingFilter calls `startActive` on request, not does not close the activated `Scope` on response. This leaves incorrect Scope in ThreadLocalScopeManager and breaks closing of other (activated earlier) scopes.

### PR DESCRIPTION
**Pull request by pavolloffay**
Fixes #78 

There are two solutions:
* do not activate span - what is implemented in this PR
* activate span. This has an advantage that other client filters can easily add data to span. - However this does not work because CXF response filter in async client is executed in a different thread so the scope cannot be closed.

cc @mabn

### CODE REVIEW

**Comment by mabn** [comment]
+1
Not activating is better because it solves the problem with ProcessingExceptions which cannot be intercepted (https://github.com/opentracing-contrib/java-jaxrs/issues/30) and would also leave the scope without closing it.

**Comment by pavolloffay** [comment]
You are right, I thought that exception is thrown before the request filter, but it's not. So this is a much better option.

File: opentracing-jaxrs2/src/main/java/io/opentracing/contrib/jaxrs2/client/ClientTracingFilter.java [hunk 1]
```diff
@@ -2,6 +2,7 @@
 
 import static io.opentracing.contrib.jaxrs2.internal.SpanWrapper.PROPERTY_NAME;
 
+import io.opentracing.Scope;
```
Comment (objectiser) [inline opentracing-jaxrs2/src/main/java/io/opentracing/contrib/jaxrs2/client/ClientTracingFilter.java]: Doesn't look like this is needed.

File: opentracing-jaxrs2/src/main/java/io/opentracing/contrib/jaxrs2/client/ClientTracingFilter.java [hunk 2]
```diff
@@ -61,7 +62,7 @@ public void filter(ClientRequestContext requestContext) throws IOException {
                 .asChildOf(parentSpanContext);
         }
 
-        Span span = spanBuilder.startActive(false).span();
+        Span span = spanBuilder.start();
```
Comment (objectiser) [inline opentracing-jaxrs2/src/main/java/io/opentracing/contrib/jaxrs2/client/ClientTracingFilter.java]: Based on the previous comments on the PR - what happens if an exception is thrown? If the scope wouldn't be closed, this also means the span is not finished?

File: opentracing-jaxrs2-itest/common/src/main/java/io/opentracing/contrib/jaxrs2/itest/common/AbstractClientTest.java [hunk 3]
```diff
@@ -56,14 +65,15 @@ protected void initTracing(ServletContextHandler context) {
     public void testDefaultConfiguration() {
         MockTracer mockTracer = new MockTracer(new ThreadLocalScopeManager(), Propagator.TEXT_MAP);
```
Comment (objectiser) [inline opentracing-jaxrs2-itest/common/src/main/java/io/opentracing/contrib/jaxrs2/itest/common/AbstractClientTest.java]: Not related to this PR, but could simplify this to just use default constructor.

File: opentracing-jaxrs2/src/main/java/io/opentracing/contrib/jaxrs2/client/ClientTracingFilter.java (hunk 2 above)
Comment (pavolloffay) [reply opentracing-jaxrs2/src/main/java/io/opentracing/contrib/jaxrs2/client/ClientTracingFilter.java]: yes, there is an issue for it and TODO in the test
